apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: h1la3qb1i-go-gitops
  description: This is GitOps manifest for h1la3qb1i-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: h1la3qb1i-go
    janus-idp.io/tekton: h1la3qb1i-go 
    backstage.io/kubernetes-id: h1la3qb1i-go 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:h1la3qb1i-go
